app/budgets/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, DecimalField
from wtforms.validators import DataRequired, Optional
from datetime import datetime, date
from app.models import Budget


class BudgetForm(FlaskForm):

    # Generate months dynamically
    months = [(str(month), datetime(1900, month, 1).strftime('%B'))
              for month in range(1, 13)]

    # Generate years dynamically from the current year to current year + 5 more years
    current_year = datetime.now().year
    years = [(str(year), str(year))
             for year in range(current_year, current_year + 6)]

    month = SelectField('Month', choices=months, validators=[DataRequired()])
    year = SelectField('Year', choices=years, validators=[DataRequired()])

    submit = SubmitField('Create')

    # Define a DecimalField for each category with a default value of 0
    food_limit = DecimalField('Food_limit', default=0,
                              validators=[Optional()])
    grocery_limit = DecimalField(
        'Grocery_limit', default=0, validators=[Optional()])
    medical_limit = DecimalField(
        'Medical_limit', default=0, validators=[Optional()])
    bills_limit = DecimalField(
        'Bills_limit', default=0, validators=[Optional()])
    entertainment_limit = DecimalField(
        'Entertainment_limit', default=0, validators=[Optional()])
    shopping_limit = DecimalField(
        'Shopping_limit', default=0, validators=[Optional()])
    travel_limit = DecimalField(
        'Travel_limit', default=0, validators=[Optional()])
    debt_limit = DecimalField('Debt_limit', default=0,
                              validators=[Optional()])
    loan_limit = DecimalField('Loan_limit', default=0,
                              validators=[Optional()])
    other_limit = DecimalField(
        'Other_limit', default=0, validators=[Optional()])

    def limits_to_dict(self):
        """Serializes category limits data to json/dict"""
        limits = {}
        for field_name, field in self._fields.items():
            if field_name.endswith('_limit'):
                # Strip '_limit' from the field name to get the category name
                category_name = field_name.replace('_limit', '')
                # Use the field's data for the value, defaulting to 0 if it's None
                limits[category_name] = float(field.data if field.data is not None else 0)
        return limits
    
    def limit_sum(self):
        """Returns the sum of all limits."""
        total_sum = 0
        for field_name, field in self._fields.items():
            if field_name.endswith('_limit'):
                # Add the field's data to the total sum. The data will be `0` by default if not entered.
                total_sum += field.data if field.data is not None else 0
        return total_sum
    
    def fill_from_budget(self, budget: Budget):
        """Fills the form with the given budget's data"""
        self.month.data = str(budget.month)
        self.year.data = str(budget.year)
        self.food_limit.data = budget.limits_dict.get('food', 0)
        self.grocery_limit.data = budget.limits_dict.get('grocery', 0)
        self.medical_limit.data = budget.limits_dict.get('medical', 0)
        self.bills_limit.data = budget.limits_dict.get('bills', 0)
        self.entertainment_limit.data = budget.limits_dict.get('entertainment', 0)
        self.shopping_limit.data = budget.limits_dict.get('shopping', 0)
        self.travel_limit.data = budget.limits_dict.get('travel', 0)
        self.debt_limit.data = budget.limits_dict.get('debt', 0)
        self.loan_limit.data = budget.limits_dict.get('loan', 0)
        self.other_limit.data = budget.limits_dict.get('other', 0)
        

app/budgets/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'budgets',
    __name__,
    url_prefix='/budgets'
)

from app.budgets import routes

app/budgets/routes.py
from calendar import month_name
from flask import render_template, flash, redirect, url_for, request, session, current_app, abort
from app.budgets import blueprint
from app.budgets.util import get_category_emote
from app.budgets.forms import BudgetForm

import sqlalchemy as sa
from app import db
from app.models import Account, Record, Budget
from collections import defaultdict

from flask_login import current_user, login_required
from calendar import month_name

@blueprint.route("/")
@login_required
def home():
    # get the latest budget
    latest_budget = db.session.query(
        Budget
    ).filter(
        Budget.user == current_user
    ).order_by(
        Budget.year.desc(),
        Budget.month.desc()
    ).first()

    if latest_budget:
        # view latest added budget if there is one
        return redirect(url_for('budgets.view', year=latest_budget.year, month=latest_budget.month))
    
    months = []
    # render empty budget page if user has no budgets at all
    return render_template('budgets/budgets_empty.html', legend='empty', year=0, all_budgets=months, month=0 )


@blueprint.route("/new", methods=['GET', 'POST'])
@login_required
def create():
    form = BudgetForm()

    if form.validate_on_submit():
        if Budget.find_from_user_and_month(
            current_user.id, int(form.year.data), int(form.month.data)
        ):
            flash(f'Budget for {month_name[int(form.month.data)]} {form.year.data} already exists', 'danger')
            return redirect(url_for('budgets.create'))
        
        limits = form.limits_to_dict()
        amount = form.limit_sum()
        year = int(form.year.data)
        month = int(form.month.data)
        budget = Budget(
            year = year,
            month = month,
            amount = amount,
            limits_dict = limits,
            user = current_user
        )
        db.session.add(budget)
        db.session.commit()
        
        flash(f'Budget for {month} {year} created', 'success')
        return redirect(url_for('budgets.view', year=year, month=month))

    return render_template('budgets/budget_setting.html', form=form, legend="create")

@blueprint.route("/<int:year>/<int:month>/setting", methods=['GET', 'POST'])
@login_required
def setting(year, month):

    # retreive budget instance for the given year and month
    budget = db.session.query(
        Budget
    ).filter(
        Budget.user == current_user,
        Budget.year == year,
        Budget.month == month
    ).first()
    if budget is None:
        abort(404)

    form = BudgetForm()
    form.month.data = str(month)
    form.year.data = str(year)

    if form.validate_on_submit():
        budget.limits_dict = form.limits_to_dict()
        budget.amount = form.limit_sum()
        
        db.session.commit()
        
        flash(f'Budget for {month_name[month]} {year} updated', 'success')
        return redirect(url_for('budgets.view', year=year, month=month))
    else:
        current_app.logger.debug(form.errors)
    
    form.fill_from_budget(budget)
    form.submit.label.text = "Update"

    return render_template('budgets/budget_setting.html', form=form, legend="update", month=month, year=year)

@blueprint.route("/<int:year>/<int:month>", methods=['GET', 'POST'])
@login_required
def view(year, month):
    current_app.logger.debug(month)

    # retreive budget instance for the given year and month
    budget = db.session.query(
        Budget
    ).filter(
        Budget.user == current_user,
        Budget.year == year,
        Budget.month == month
    ).first()
    if budget is None:
        abort(404)

    # retreive expenses by category for the given year and month
    expenses_by_category = db.session.query(
        Record.category,
        sa.func.sum(Record.amount).label('total_amount'),
    ).join(Account)                                     \
    .filter(
        Account.user == current_user,
        Record.type == 'expense',
        sa.extract('year', Record.date) == year,
        sa.extract('month', Record.date) == month
    ).group_by(
        Record.category
    ).all()

    # retreive all months for for the given year with budgets
    budgets_year = db.session.query(
        Budget.month
    ).filter(
        Budget.user == current_user,
        Budget.year == year
    ).distinct().order_by(Budget.month).all()
    # transform to dictionary
    budgets_year = [t_month[0] for t_month in budgets_year]
    
    # retrieve all of the user's budgets, select only the year and months
    all_budgets = db.session.query(
        Budget.year,
        Budget.month
    ).filter(
        Budget.user == current_user
    ).distinct().order_by(Budget.month).all()
    # transform to dictionary
    budgets_dict = defaultdict(list)
 
    for x_year, y_month in all_budgets:
        budgets_dict[x_year].append(y_month)

    # Initialize budgets dictionary with category limits from budget_instance
    budgets = defaultdict(lambda: {"limit": 0, "spent": 0})
    for category, limit in budget.limits_dict.items():
        if limit != 0:
            budgets[get_category_emote(category)]["limit"] = float(limit)

    # Update the "spent" values based on expenses_by_category
    for category, total_amount in expenses_by_category:
        category_with_emoji = get_category_emote(category.lower())
        
        if category_with_emoji in budgets: 
            budgets[category_with_emoji]["spent"] = float(total_amount) * -1
    
    # month name of month 
    month_names = month_name[month]
    total_spent = sum([budgets[category]["spent"] for category in budgets])
    remaining = float(budget.amount) - total_spent


    next_month = month + 1
    next_year = year

    if next_month > 12:
        next_month = 1  # Wrap around to January
        next_year = year + 1

    previous_month = month - 1
    previous_year = year

    if previous_month == 0:
        previous_month = 12  # Wrap around to December
        previous_year = year - 1
    
    user_id = current_user.id
    
    next_month_budget = Budget.find_from_user_and_month(user_id, next_year, next_month)
    previous_month_budget = Budget.find_from_user_and_month(user_id, previous_year, previous_month)

    has_next, has_prev = False, False

    if next_month_budget:
        has_next = True

    if previous_month_budget:
        has_prev = True
 

    return render_template(
        'budgets/budgets.html',
        budgets=budgets, 
        month_name=month_names, 
        month=month,
        year=year,
        remaining=remaining,
        total_spent=total_spent, 
        all_budgets=budgets_dict,
        has_next=has_next,
        has_prev=has_prev,)


app/templates/budgets/budget_setting.html
{% extends 'layouts/base.html' %}

{% block title %} Budget Setting {% endblock title %}

{% block content %}
<div class="container-fluid p-0">
 
    {% if legend == "update" %}
      <a href="{{ url_for('budgets.view', year=year, month=month) }}" class="btn btn-light">
        <i data-feather="arrow-left"></i><span class="ms-2">Back</span>
      </a>
    {% endif %}
    <h1 class="h3 mb-3">{{ legend | capitalize }} Budget</h1>

  <div class="row justify-content-md-center">
    <div class="col-12 col-sm-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title mb-0">{{ legend | capitalize }} Budget Setting</h5>

        </div>
        <div class="card-body">
            <form action="" method="post" novalidate>
              {{ form.hidden_tag() }}
              <div class="d-flex flew-row">
                <div class="input-group mb-3">
                  <span class="input-group-text">Year</span>
                  {% if legend == "update" %}
                    {{ form.year(class="form-select", disabled='disabled') }}
                  {% else %}
                    {{ form.year(class="form-select" + (' is-invalid' if form.year.errors else '') ) }}
                  {% endif %}
                  <div class="invalid-feedback">
                      {% for error in form.year.errors %}
                          <span> {{ error }} </span>
                      {% endfor %}
                  </div>
                </div>
                <div class="input-group mb-3">
                  <span class="input-group-text">Month</span>
                  {% if legend == "update" %}
                    {{ form.month(class="form-select", disabled='disabled') }}
                  {% else %}
                    {{ form.month(class="form-select" + (' is-invalid' if form.month.errors else '') ) }}
                  {% endif %}
                  <div class="invalid-feedback">
                      {% for error in form.month.errors %}
                          <span> {{ error }} </span>
                      {% endfor %}
                  </div>
                </div>
                </div>
              <div class="container">
                {% for field in form  %}
                  {% if field.name.endswith('_limit') %}
                    <div class="row mb-3 px-sm-3">
                      <div class="col-12 col-sm-3">
                        <label class="form-label">{{ field.label.text.replace('_', ' ') }}</label>
                      </div>
                      <div class="col-12 col-sm-9">
                        <div class="input-group mb-3">
                          <span class="input-group-text">$</span>
                          {{ field(class="form-control" + (' is-invalid' if field.errors else ''), placeholder="199") }}
                          <div class="invalid-feedback">
                            {% for error in field.errors %}
                                {{ error }} 
                            {% endfor %}
                          </div>
                        </div>
                      </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="d-flex flex-row-reverse">
                      {{ form.submit(class="btn btn-primary") }}
                    </div>
              </div>
                
            </form>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

{% block javascripts %}
  
{% endblock javascripts %}

app/templates/budgets/budgets.html
{% extends 'layouts/base.html' %}

{% block title %} Budget {% endblock title %}

{% if legend == "empty" %}
  
{% else %}
  
{% endif %}

{% block content %}
<div class="container-fluid p-0">

 
  <!-- <h1 class="h3 mb-3">Budgets</h1> -->
  <div class="d-flex flex-row">

    {% for b_year in all_budgets.keys() %}
      {% if b_year == year %}
        <h1 class="h3 me-2">
          <span class="fw-bold">
            <a href="{{ url_for('budgets.view', month=1, year=b_year ) }}" class="text-dark">{{ b_year }}</a>
          </span>
        </h1>
      {% else %}
        <h1 class="h3 fw-bold me-2"><a href="{{ url_for('budgets.view', month=1, year=b_year ) }}" class="text-secondary">{{ b_year }}</a></h1>
      {% endif %}
    {% endfor %}
  <h1 class="h3 mb-3"> Budgets</h1>

  </div>
  <div class="btn-toolbar mb-2">
    <div class="my-2 my-md-0 btn-group me-2 overflow-x-auto">
      {% for smonth in range(1, 13) %}
      {% set month_name = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][smonth-1] %}
      <a href="{{ url_for('budgets.view', month=smonth, year=year) }}" class="btn btn-light {{ 'fw-bold' if smonth == month }} {{ 'disabled' if smonth not in all_budgets[year] }}">{{ month_name }}</a>
    {% endfor %}
    </div>
    <div class="btn-group me-2">
      <a href="{{ url_for('budgets.view', month=month-1, year=year) }}" class="btn btn-dark {{ 'disabled' if month == 1 or not has_prev }}">Prev</a>
      <a href="{{ url_for('budgets.view', month=month+1, year=year) }}" class="btn btn-dark {{ 'disabled' if month == 12 or not has_next }}">Next</a>
    </div>
    <div class="btn-group me-2">
      <a href="{{ url_for('budgets.create', year=2024) }}" class="btn btn-success">
        <i data-feather="plus"></i><span class="ms-2">New Budget</span>
      </a>
    </div>

  </div>
  

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header p-5">
          <div class="row justify-content-between align-items-center">
            <div class="col-sm-12 col-md-3 text-center text-md-start">
              <h1 class="fs-1">{{ month_name }}'s Budget</h1>
            </div>
            <div class="col-6 col-sm-6 col-md-3">
              <div class="d-flex flex-column align-items-center">
                <h5 class="text-muted">Remaning</h5>
                <h5 class="text-primary">$ {{ "{:,.2f}".format(remaining) }}</h5>
              </div>
            </div>
            <div class="col-6 col-sm-6 col-md-3">
              <div class="d-flex flex-column align-items-center">
                <h5 class="text-muted">Total Spent</h5>
                <h5 class="text-danger">$ {{ "{:,.2f}".format(total_spent) }}</h5>
              </div>
            </div>
            <div class="col-sm-12 col-md-3 text-center text-md-end">
              <a href="{{ url_for('budgets.setting', year=year, month=month) }}" class="btn btn-light text-center">
                <i data-feather="tool"></i><span class="ms-2">Budget Setting</span>
              </a>
            </div>
          </div>
        </div>
        <div class="card-body px-0">
          {% for category, detail in budgets.items()  %}
          {% set percent = (((detail.spent / detail.limit)*100) | round(2)) %}
          <div class="row px-4">
            <div class="col-4">
              <h5 class="text-muted">{{ category }}</h6>
            </div>
            <div class="col-8">
              <div class="progress" style="height: 105%" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ percent }}%"><span class="text-end me-3">{{ percent }}%</span></div>
              </div>
            </div>
          </div>
          <div class="row px-4">
            <div class="col-12 col-md-4">
              <h5>$ {{ "{:,.2f}".format(detail.limit) }}</h5>
            </div>
            <div class="col-12 col-md-8">
              <div class="row justify-content-between">
                <div class="col-4">
                  <span class="text-primary">$ {{ "{:,.2f}".format(detail.spent) }}</span>
                </div>
                <div class="col-auto">
                  <span class="fw-bold">$ {{ "{:,.2f}".format(detail.limit - detail.spent) }}</span>
                </div>
              </div>
            </div>
          </div>
          <hr>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}
{% block javascriptts %}
<script>
  
</script>
{% endblock javascriptts %}

app/templates/budgets/budgets_empty.html
{% extends 'layouts/base.html' %}

{% block title %} Budget {% endblock title %}

{% block content %}
<div class="container-fluid p-0">

 
  <!-- <h1 class="h3 mb-3">Budgets</h1> -->
  <div class="d-flex flex-row">

    <h1 class="h3 me-2">
        <span class="fw-bold">
            <a href="{{ url_for('budgets.view', month=1, year=year ) }}" class="btn btn-secondary disabled">{{ year }}</a>
        </span>
    </h1>
    <h1 class="h3 mb-3"> Budgets</h1>

  </div>
  <div class="btn-toolbar mb-2">
    <div class="btn-group me-2">
        {% for month in range(1, 13) %}
        {% set month_name = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][month-1] %}
        <a href="{{ url_for('budgets.view', month=month, year=year) }}" class="btn btn-light {{ 'disabled' if month not in all_budgets }}">{{ month_name }}</a>
      {% endfor %}
    </div>
    <div class="btn-group me-2">
        
      <a href="{{ url_for('budgets.view', month=month-1, year=year) }}" class="btn btn-dark {{ 'disabled' if month == 1 or legend == 'empty' }}">Prev</a>
      <a href="{{ url_for('budgets.view', month=month+1, year=year) }}" class="btn btn-dark {{ 'disabled' if month == 12 or legend == 'empty' }}">Next</a>
    </div>
    <div class="btn-group me-2">
      <a href="{{ url_for('budgets.create', year=2024) }}" class="btn btn-success">
        <i data-feather="plus"></i><span class="ms-2">New Budget</span>
      </a>
    </div>

  </div>
  

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header d-flex flex-row justify-content-between align-items-center p-5">
            <h3><span class="badge bg-secondary">No budgets</span></h3>
            <a href="{{ url_for('budgets.create', year=2024) }}" class="btn btn-success">
                <i data-feather="plus"></i><span class="ms-2">New Budget</span>
              </a>
        </div>
        <div class="card-body px-0">
          
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}