app/records/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'records',
    __name__,
    url_prefix='/r'
)

from app.records import routes

app/records/routes.py
# -*- encoding: utf-8 -*-

from venv import create
from flask import render_template, flash, redirect, url_for, request, abort
from app.records import blueprint
from app.main.util import get_accounts, get_categories
from app.main.forms import RecordForm
from app.main.forms import create_record
from app.utils import HXRedirect

from app import db
from app.models import  Record

from flask_login import current_user, login_required
import logging
logging.basicConfig(level=logging.DEBUG)

# TODO: remove
@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return ""

@blueprint.get('/modal')
@login_required
def modal():
    prev_url = request.args.get('redirect', default=None, type=str)
    rtype = request.args.get('rtype', default=None, type=str)
    account_id = request.args.get('acid', default=None, type=int)
    legend = request.args.get('legend', default=None, type=str)
    return render_template('records/add.html', 
                           legend=legend,
                           rtype=rtype,
                           account_id=account_id, 
                           prev_url=prev_url)


@blueprint.route('/add', methods=['GET','POST'])
@login_required
def add():
    record_type = request.args.get('type', default=None, type=str)
    # passing an account id is optional
    acid = request.args.get('acid', default=None, type=int)
    prev_url = request.args.get('prev', default=None, type=str)
    logging.debug(f'record_type: {record_type}')
    logging.debug(f'acid: {acid}')
    logging.debug(f'prev_url: {prev_url}')

    form = RecordForm()
    form.type.data = 'expense'

    if acid and not current_user.has_account(acid):
        abort(404)
    
    form.account.data = acid
    # TODO: throw error on invalid record type
    form.account.choices = get_accounts()

    form.category.choices = get_categories(record_type)

    if form.validate_on_submit():
        form.type.data = record_type
        record = create_record(form)
        db.session.add(record)
        db.session.commit()
        flash(f'{type} successfully added.', 'success')
        return HXRedirect(prev_url)


    return render_template('records/form.html', form=form, rtype=record_type, account_id=acid, prev_url=prev_url)

@blueprint.route('/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    form = RecordForm()
    form.category.choices = get_categories("expense")
    form.account.choices = get_accounts()
    record = Record.query.get_or_404(id)

    redirect_url = url_for('incomes.home')
    if record.type == 'expense':
        redirect_url = url_for('expenses.home')
    
    if request.method == 'POST':
        if '_method' in request.form and request.form['_method'] == 'DELETE':
            db.session.delete(record)
            db.session.commit()
            flash('Record Successfully deleted', 'danger')
            return redirect(url_for(redirect_url))


    if form.validate_on_submit():
        record.name = form.name.data
        record.amount = form.amount.data
        if record.type == 'expense' and record.amount > 0:
            record.amount = -record.amount
        record.category = form.category.data
        record.date = form.date_spent.data
        record.note = form.note.data
        record.account_id = form.account.data

        db.session.commit()

        flash('Record Successfully updated', 'success')
        return redirect(url_for('records.edit', id=record.id))

    # pre-populate data with existing record details
    form.fill_from_record(record)
    form.submit.label.text = 'Update'
    legend = "Expense" if record.type == 'expense' else "Income"

    return render_template('record_item_page.html', form=form, item=record, legend=legend)

@blueprint.delete('/delete/<int:id>')
@login_required
def delete(id):
    sub = Record.query.get_or_404(id)
    db.session.delete(sub)
    db.session.commit()
    return ""

app/templates/records/add.html
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
     
        <h5 class="modal-title fw-bold">{{ legend }}</h5>
     
      </div>
      <div class="modal-body">
        
        <div id="addrecord" 
          hx-get="{{ url_for('records.add', type=rtype, acid=account_id, prev=prev_url) }}" 
          hx-trigger="load delay:100ms" 
          hx-target="#contains" hx-swap="innerHTML" 
        >
          
          <div id="contains">
  
          </div>
          <!-- end contains -->
        </div>
      </div>
    </div>
  </div>

app/templates/records/form.html
<form id="record_form" hx-post="{{ url_for('records.add', type=rtype, acid=account_id, prev=prev_url ) }}" novalidate>
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {{ form.name(class="form-control" + (' is-invalid' if form.name.errors else ''), placeholder="Cat Food") }}
        <div class="invalid-feedback">
            {% for error in form.name.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </div>
    </div>
    {{ form.amount.label(class="form-label") }}
    <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        {{ form.amount(class="form-control" + (' is-invalid' if form.amount.errors else ''), placeholder="199") }}
        <div class="invalid-feedback">
            {% for error in form.name.errors %}
                {{ error }} 
            {% endfor %}
        </div>
    </div>
    <div class="mb-3">
        {{ form.date_spent.label(class="form-label") }}
        {{ form.date_spent(class="form-control" + (' is-invalid' if form.date_spent.errors else '') ) }}
        <div class="invalid-feedback">
            {% for error in form.date_spent.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </div>
    </div>
    <div class="mb-3">
        {{ form.category.label(class="form-label") }}
        {{ form.category(class="form-select" + (' is-invalid' if form.category.errors else '') ) }}
        <div class="invalid-feedback">
            {% for error in form.category.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </div>
    </div>
    <!-- <div class="mb-3">
        {{ form.account.label(class="form-label") }}
        {{ form.account(class="form-select" + (' is-invalid' if form.account.errors else '') ) }}
        <div class="invalid-feedback">
            {% for error in form.account.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </div>
    </div> -->
    <div class="input-group mb-3">
        <span class="input-group-text">Notes</span>
        {{ form.note(class="form-control" + (' is-invalid' if form.note.errors else ''), placeholder="Additional notes") }}
        <div class="invalid-feedback">
            {% for error in form.note.errors %}
                <span> {{ error }} </span>
            {% endfor %}
        </div>
    </div>
    <!-- hidden field for type -->
    
    <!-- submit -->
    <div class="d-flex flex-row-reverse my-3">
        {{ form.submit(class="btn btn-primary ms-2") }}
        <button type="button" class="btn btn-secondary ms-2" data-bs-dismiss="modal">Close</button>
    </div>
</form>